### PR TITLE
fix: modified text for admin password

### PR DESCRIPTION
**Pull request by imprateeksh**
### Description
Refer  [Issue-6615](https://github.ibm.com/GoldenEye/issues/issues/6615)
Fixed the below:
- Remove text mentioning range of admin password
- Modified the `pr_tests` to include passwords for administrator as greater than or equal to 15 characters.

### Release required?

- [ ] No release
- [x] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [x] If relevant, a test for the change is included or updated with this PR.
- [x] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by imprateeksh** [comment]
Closing the PR as another [PR](https://github.com/terraform-ibm-modules/terraform-ibm-icd-elasticsearch/pull/53) is merged with the relevant changes.

**Comment by shemau** [comment]
re-opening to make the testing process consistent with other terraform-icd modules.

**Review by shemau — APPROVED** [review]
LGTM

**Review by ocofaigh — APPROVED** [review]

**Comment by ocofaigh** [comment]
@imprateeksh The pipeline failed with:
```
TestRunCompleteExample 2023-12-05T09:55:06Z retry.go:99: Returning due to fatal error: FatalError{Underlying: error while running command: exit status 1; ╷
│ Error: There are documents in the index (or the index could not be , set force_destroy to true to allow destroying.
│ 
│ 
╵}
```

This is probably unrelated to any changes in this PR, however can you address this in your PR setting `force_destroy` to `true` in the complete example `elasticsearch_index` resource to prevent it from happening again?

**Comment by imprateeksh** [comment]
> force_destroy

I believe this flag is supposed to be added as part of the field `TerraformVars`.

**Comment by imprateeksh** [comment]
For `force_destroy=true`, I understood it differently hence made a silly change now reverted back.

**Comment by imprateeksh** [comment]
I think I may not be able to make this change as I am not having access to view repo settings to make further PR related changes. Settings tab is not shown for me.

**Comment by ocofaigh** [comment]
@imprateeksh Can you resolve conflicts for this please?

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
