### PR TITLE
fix: error: Invalid template interpolation value

### PR DESCRIPTION
**Pull request by akocbek**
### Description
Issue: https://github.com/terraform-ibm-modules/terraform-ibm-icd-elasticsearch/issues/296

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by ocofaigh** [comment]
Strange, the fscloud example failed on idempotent failure:
```
        	Messages:   	Resource(s) identified to be updated 
        	            	Name: elasticsearch_tag
        	            	Address: module.elasticsearch.module.elasticsearch.ibm_resource_tag.elasticsearch_tag[0]
        	            	Actions: [update]
        	            	DIFF:
        	            	  Before: 
        	            		{"tags":"SECURE_VALUE_HIDDEN_HASH:-f21d72e82ece0452202370f3b19ecf8dcab590f0d221203bd288dc7e"}
        	            	  After: 
        	            		{"tags":"SECURE_VALUE_HIDDEN_HASH:-48b3f952b63bfa385b736ec6d98bde68b37ed7f3528ea11bea11b9ed"}
```

Going to retry..

**Comment by akocbek** [comment]
```Error: [0m Error: [ERROR] Error deleting resource key: Gone with resp code: {
│     "StatusCode": 410,
│     "Headers": {
│         "Cache-Control": [
│             "max-age=0, no-cache, no-store"
│         ],
│         "Content-Length": [
│             "3"
│         ],
│         "Content-Type": [
│             "application/json"
│         ],
│         "Date": [
│             "Wed, 25 Sep 2024 13:30:43 GMT"
│         ],
│         "Expires": [
│             "Wed, 25 Sep 2024 13:30:43 GMT"
│         ],
│         "Pragma": [
│             "no-cache"
│         ],
│         "Request-Id": [
│             "626c-8a855dccbd3ba318"
│         ],
│         "Retry-After": [
│             "0"
│         ],
│         "Server": [
│             "istio-envoy"
│         ],
│         "Set-Cookie": [
│             "ak_bmsc=082C2EFFB8580EB188A11BCA9572D579~000000000000000000000000000000~YAAQk2rcF7dihyeSAQAA5IBgKRm+44slqhnwjI+cmziOtZ8h64ilOY2m2M7hn5L75hqCchTn//AmJzGQYij7kEtXzD5/mQ84xs9uAdJ6slkzacVzvbukIyXONKREm0vkDeGQnGggJMZar6bnHPWHK77TP8ze6MDKyg0RNvlOiRkR+lNSnWiqePR5CE4FnTsIiPA2AU/WoVE0K0jydnHvl4Q4/5WEY3gZIdU58bhxo2O+eV+lpyV1Dexp+Gek0wISfyrUUhl6YOktpccjkBvxpkLKEJcwDXmM7I/cFRfX+oryZJ9AWbL7B08/0Ni1ASt5G0Kx9EhxbJCuYq5NoYjOnhojdN7PUIbrEvEZ0ngAjsgkySq/iXoS0DPaScqAUYmUzhBHbd7ehXGt0y/U; Domain=.cloud.ibm.com; Path=/; Expires=Wed, 25 Sep 2024 15:30:43 GMT; Max-Age=7200"
│         ],
│         "Strict-Transport-Security": [
│             "max-age=31536000;includeSubDomains"
│         ],
│         "Transaction-Id": [
│             "626c-0adf0ac086a5044f"
│         ],
│         "X-Content-Type-Options": [
│             "nosniff"
│         ],
│         "X-Correlation-Id": [
│             "626c-0adf0ac086a5044f"
│         ],
│         "X-Envoy-Upstream-Service-Time": [
│             "76"
│         ],
│         "X-Op-Completion-Time": [
│             ""
│         ],
│         "X-Ratelimit-Limit": [
│             "100"
│         ],
│         "X-Ratelimit-Remaining": [
│             "95"
│         ],
│         "X-Ratelimit-Reset": [
│             "0"
│         ]
│     },
│     "Result": {},
│     "RawResult": null
│ }
│ 
│ 
```

retrying..

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
