### PR TITLE
chore: remove deprecated version 7.17

### PR DESCRIPTION
**Pull request by Aashiq-J**
### Description

7.17 version no-longer available.

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [x] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

- remove support for deprecated elasticsearch version 7.17

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Review by shemau — CHANGES_REQUESTED** [review]
The code change looks good.

The PR description is incomplete. AFAIK 7.17 is not removed, the documentation says it is available until August 2024 (https://cloud.ibm.com/docs/cloud-databases?topic=cloud-databases-versioning-policy), the UI and CLI still list it as stable (not even deprecated).

The release notes should be clear, should existing 7.17 consumers upgrade, if so how? Should they lock into the older version of the module until the database is upgraded?

**Comment by Aashiq-J** [comment]
@shemau ,
I'm not sure, why 7.17 is still available from the UI because when trying to deploy using terraform getting the below error
image

**Review by shemau — APPROVED** [review]
Further investigation suggests that the service is not offering 7.17 even with older providers, so I think this is good to go.

**Pull request merged**
