### PR TITLE
fix: password validation not start with special

### PR DESCRIPTION
**Pull request by shemau**
### Description

#325

The random_password resource does not offer the flexibility of restricting the first character.

Adopted the following logic:

- if first char is - replace with J
- else
  - if first char is _ replace with K
  - else use asis

This should not impact any existing users, since the DA failed if the first character was wrong.

### Release required?

- [ ] No release
- [x] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

Fix a bug to avoid the administrator password generated by the DA starting with a special character.

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by shemau** [comment]
Marking as draft whilst more extensive local testing/validation is undertaken.

**Comment by shemau** [comment]
```hcl
admin_pass2 = "GwKoQIn86UsapEzu4v5a4Oqx_w53L10n"
admin_pass3 = "GwKoQIn86UsapEzu4v5a4Oqx_w53L10n"
admin_pass2 = "CT4tlk3VWhMf2NNp93CKDTeqy49qTcMs"
admin_pass3 = "CT4tlk3VWhMf2NNp93CKDTeqy49qTcMs"
admin_pass2 = "_Cr0R7HXrQXLPyV9IWHDuSY20qKhUA9h"
admin_pass3 = "KCr0R7HXrQXLPyV9IWHDuSY20qKhUA9h"
admin_pass2 = "8vkhWRPX5uSHPidnk8mjieQ3WRjf2VE5"
admin_pass3 = "8vkhWRPX5uSHPidnk8mjieQ3WRjf2VE5"
admin_pass2 = "xBqv1pis69dnjtUyojCyVUO6GJM1j5RI"
admin_pass3 = "xBqv1pis69dnjtUyojCyVUO6GJM1j5RI"
admin_pass2 = "BffOKeh3RanY4OapEu48Is8ss8mCk3jw"
admin_pass3 = "BffOKeh3RanY4OapEu48Is8ss8mCk3jw"
admin_pass2 = "-4KHq_9G68eRp4aQvnR9hgRTJt3yFF5i"
admin_pass3 = "J4KHq_9G68eRp4aQvnR9hgRTJt3yFF5i"
admin_pass2 = "h8kYGym7khL_Opl_6YmdVNoGn6yQoH9b"
admin_pass3 = "h8kYGym7khL_Opl_6YmdVNoGn6yQoH9b"
admin_pass2 = "Oi_4qf7Fy9RKKffJ70U37wMp4jklhFRo"
admin_pass3 = "Oi_4qf7Fy9RKKffJ70U37wMp4jklhFRo"
```

The code was run, marking the secrets as non-sensitive and outputting the values before and after manipulation. This shows both `-` and `_` being converted and due to the random nature many others including the characters at other places.

**Review by jor2 — DISMISSED** [review]

**Review by jor2 — APPROVED** [review]
LGTM

**Pull request merged**
