### PR TITLE
doc: added complex variables description

### PR DESCRIPTION
**Pull request by imprateeksh**
### Description

This PR addresses [Issue-205](https://github.com/terraform-ibm-modules/terraform-ibm-icd-elasticsearch/issues/205) i.e.  to provide a supporting document to explain the complex object types used as part of DA.

### Release required?

- [x] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [x] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by SirSpidey** [comment]
I'm not going to get to this today. On my Tuesday list.

**Comment by imprateeksh** [comment]
Only the user roles + type combination is giving error. I have updated document to refer the link and removed `role` from our doc.
Query related to user roles and user types is asked in [slack thread](https://ibm-cloudplatform.slack.com/archives/C534XRCF3/p1720126073608369?thread_ts=1720125740.705869&cid=C534XRCF3)

**Review by ocofaigh — CHANGES_REQUESTED** [review]
The applicable variable descriptions need to be updated to point to the new doc

**Comment by ocofaigh** [comment]
@imprateeksh Did can you show proof that these example snippets you added work with the DA? If you recall when I tested last time, they failed

**Comment by imprateeksh** [comment]
> @imprateeksh Did can you show proof that these example snippets you added work with the DA? If you recall when I tested last time, some failed

Yes sure @ocofaigh. 
Except for the mismatch happening in case of user types + roles combination, which is already asked in slack thread, all the values provided are working fine.

Let me provide screen grabs of all the inputs provided: 
**1. Service Credentials**
image

**2. Users**
image

image

**3. Autoscaling**
image


**4. Locally providing the same as default values in the `complete` example:**
Result is here- [complete_example_plan.txt](https://github.com/user-attachments/files/16108090/complete_example_plan.txt)

image

image

image

image

**Review by SirSpidey — DISMISSED** [review]
My edits were incorporated into this PR from #217

**Review by shemau — COMMENTED** [review]
Should the descriptions for `users` and `autoscaling` variables (in the DA variables.tf) be updated to link to this document?

The description is included the UI, so it can include a link... reference: keys variable in kms-all-inclusive.

**Comment by ocofaigh** [comment]
I also mentioned same as Steve in above [comment](https://github.com/terraform-ibm-modules/terraform-ibm-icd-elasticsearch/pull/216#pullrequestreview-2160310622) - the DA variable descriptions need to point to the doc

**Comment by imprateeksh** [comment]
@shemau @ocofaigh - I have made the change to reference the document in the variable description. Could you please review once again?

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
