### PR TITLE
fix: small fixes around input DA variables

### PR DESCRIPTION
**Pull request by akocbek**
### Description
Issue: https://github.com/terraform-ibm-modules/terraform-ibm-icd-elasticsearch/issues/297

- [x] existing_kms_key_crn is currently in the required list but should be moved to optiona
- [x] move use_existing_resource_group next to resource_group_name in ui (on required).
- [x] elser_model_type -> this is only applicable if plan is platinum (not for enterprise). At minumum indicate it in the description of the variable.
- [x] skip_es_sm_auth_policy -> use full service name when they are not obvious to typical end-user (skip_elastic_search_secret_manager_auth_policy or skip_elastic_search_to_secret_manager_auth_policy)
- [x] existing_db_instance_crn -> use elastic_search instead of db for consistency in naming.
- [x] skip_iam_authorization_policy and skip_es_sm_auth_policy are inconsistent in term of naming.
- [x] group related inputs together in ui - eg: all kms related input together.

### Release required?

- [ ] No release
- [x] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Review by ocofaigh — COMMENTED** [review]
`elasticsearch` is one word, so personally I would remove the underscores from the variable names. Feel free to ask other team members what they think though

**Comment by akocbek** [comment]
```
   "Result": {
        	            	│         "errors": [
        	            	│             {
        	            	│                 "code": "zone_used_by_rule",
        	            	│                 "message": "The network zone '53e58ce8397c1fbc6b61497b734effa5' is referenced by one or more rules and cannot be deleted."
        	            	│        
```

rerunning

**Comment by ocofaigh** [comment]
@akocbek what happened to this one? Is it good to go? If so, can you update the release notes section of the PR description and get pipeline passing please?

**Comment by akocbek** [comment]
created new PR https://github.com/terraform-ibm-modules/terraform-ibm-icd-elasticsearch/pull/374

**Pull request closed without merging**
